In [ ]:
import torch

### Scalars

In [ ]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y, x-y, x*y, x/y, x**y

### Vectors

In [ ]:
x = torch.arange(3)
x

In [ ]:
x[2]

In [ ]:
len(x)

In [ ]:
x.shape

### Matrices

In [ ]:
A = torch.arange(6).reshape(3,2)
A

In [ ]:
A.T

In [ ]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

### Tensors

In [ ]:
torch.arange(24).reshape(2, 3, 4)

### Basic Properties of Tensor Arithmetic

In [ ]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A, A+B

In [ ]:
A*B

In [ ]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a+X, (a * X).shape

### Reduction

In [ ]:
x = torch.arange(3, dtype=torch.float32)
x, sum(x)

In [ ]:
A.shape, A.sum()

In [27]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [ ]:
A.shape, A.sum(axis=1).shape

In [26]:
A.sum(axis=[0,1]) == A.sum()

tensor(True)

In [ ]:
A.mean(), A.sum()/A.numel()

In [ ]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

### Non-Reduction Sum

In [23]:
sum_A = A.sum(axis=1, keepdims=True)
A, sum_A, sum_A.shape

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [24]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [45]:
A, A.cumsum(axis=0), A.cumsum(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 5., 7.]]),
 tensor([[ 0.,  1.,  3.],
         [ 3.,  7., 12.]]))

### Dot Products

In [46]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [47]:
torch.sum(x * y)

tensor(3.)