In [ ]:
import torch

### Scalars

In [ ]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y, x-y, x*y, x/y, x**y

### Vectors

In [ ]:
x = torch.arange(3)
x

In [ ]:
x[2]

In [ ]:
len(x)

In [ ]:
x.shape

### Matrices

In [ ]:
A = torch.arange(6).reshape(3,2)
A

In [ ]:
A.T

In [ ]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

### Tensors

In [ ]:
torch.arange(24).reshape(2, 3, 4)

### Basic Properties of Tensor Arithmetic

In [ ]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A, A+B

In [ ]:
A*B

In [ ]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a+X, (a * X).shape

### Reduction

In [ ]:
x = torch.arange(3, dtype=torch.float32)
x, sum(x)

In [ ]:
A.shape, A.sum()

In [ ]:
A.shape, A.sum(axis=0).shape

In [ ]:
A.shape, A.sum(axis=1).shape

In [ ]:
A.sum(axis=[0,1]) == A.sum()

In [ ]:
A.mean(), A.sum()/A.numel()

In [ ]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

### Non-Reduction Sum

In [49]:
sum_A = A.sum(axis=1, keepdims=True)
A, sum_A, sum_A.shape

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [ ]:
A / sum_A

In [ ]:
A, A.cumsum(axis=0), A.cumsum(axis=1)

### Dot Products

In [ ]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

In [ ]:
torch.sum(x * y)

### Matrix&ndash;Vector Products

In [ ]:
A.shape, x.shape, torch.mv(A, x), A@x

### Matrix&ndash;Matrix Multiplication

In [ ]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

### Norms

In [ ]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

In [ ]:
torch.abs(u).sum()

In [ ]:
torch.norm(torch.ones((4, 9)))

### Exercises

In [34]:
X, len(X), 24

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 2,
 24)

In [ ]:
try:
    A, A / A.sum(axis=1)
except Exception as e:
    print(A, A.sum(axis=1))
    print(e)
    
# should be keepdims=True

tensor([[0., 1., 2.],
        [3., 4., 5.]]) tensor([ 3., 12.])
The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1


In [40]:
t = torch.ones((2,3,4))
t, t.sum(axis=0), t.sum(axis=1), t.sum(axis=2)

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[4., 4., 4.],
         [4., 4., 4.]]))

In [ ]:
import numpy as np

# Frobenius
np.linalg.norm(t), np.sqrt(np.float32(2*3*4))

(np.float32(4.8989797), np.float32(4.8989797))

In [60]:
eA = torch.ones((100,200))
eB = eA * 2
eC = eA.clone()
eD = torch.stack((eA, eB, eC), dim=2)
eD[:,:,1]

tensor([[2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.],
        ...,
        [2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.]])