In [1]:
import torch

### Data Manipulation

In [4]:
x=torch.arange(12, dtype=torch.float32)
print(x)
print(x.numel())
print(x.shape)
X = x.reshape(3,4)
print(X)
z = torch.zeros((2,3,4))
print(z)
o = torch.ones(z.shape)
print(o)
r = torch.randn(3,4)
print(r)
t = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
print(t)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
12
torch.Size([12])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[ 1.0301, -0.2223, -0.8402,  0.3866],
        [-0.2550,  0.1337,  0.8542, -0.4684],
        [ 1.8309, -1.5320,  0.1790, -2.3635]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


### Indexing and Slicing

In [7]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[12., 12., 12., 12.],
         [ 8.,  9., 10., 11.]]))

In [5]:
X[1,2]=17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
X[:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### Operations

In [ ]:
torch.exp(x)

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2,2,2,2])
x+y, x-y, x*y, x/y, x**y

In [ ]:
X = torch.arange(12, dtype = torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

# Experimentation
[torch.cat((X, Y), dim=d) for d in [0,1]]

In [ ]:
X==Y

In [ ]:
X>Y

In [ ]:
X.sum()

### Broadcasting

In [ ]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

In [ ]:
a + b

In [ ]:
# Experimentation

a = torch.arange(6).reshape((3,1,2))
b = torch.arange(2).reshape((1,2,1))
a, b, a+b

### Saving Memory

In [ ]:
before = id(Y)
Y = Y+X
id(Y) == before

In [ ]:
Z = torch.zeros_like(Y)
print("id(Z):", id(Z))
Z[:] = X+Y
print("id(Z):", id(Z))


In [ ]:
before = id(X)
X += Y
id(X) == before

### Conversion to Other Python Objects

In [8]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [9]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)