In [2]:
import torch

### Scalars

In [6]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y, x-y, x*y, x/y, x**y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

### Vectors

In [9]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [10]:
x[2]

tensor(2)

In [11]:
len(x)

3

In [12]:
x.shape

torch.Size([3])

### Matrices

In [13]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [14]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [15]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### Tensors

In [16]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### Basic Properties of Tensor Arithmetic

In [4]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [18]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [19]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a+X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### Reduction

In [3]:
x = torch.arange(3, dtype=torch.float32)
x, sum(x)

(tensor([0., 1., 2.]), tensor(3.))

In [5]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [6]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [7]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [8]:
A.sum(axis=[0,1]) == A.sum()

tensor(True)

In [9]:
A.mean(), A.sum()/A.numel()

(tensor(2.5000), tensor(2.5000))

In [13]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))